### ISSUE TITLE
大佬还继续维护吗？发现一些问题

### ISSUE THREAD

**Issue by nomoneynolife** [frozleaf/RemoteControl#1]
主界面的功能，只有第一个 查看文件 是正常的， 另外在主界面添加开机启动也没有效果！

进程，注册表，管理(重启)都没有效果！

控制端是WIN7

受控端分别是WIN7 / WIN10

**Comment by misaya** [comment]
你是客户端运行身份不对吧?

**Comment by frozleaf** [comment]
已解决
