### ISSUE TITLE
how to use?

### ISSUE THREAD

**Issue by andrescastro7036** [frozleaf/RemoteControl#2]

**Comment by frozleaf** [comment]
1. 编译解决方案
2. 打开RemoteControl.Server.exe
3. 开启服务：点击“自动上线”
4. 生成客户端：点击“配置服务程序”->"客户端配置"->"生成客户端"->"保存"
5. 运行客户端：双击打开生成的客户端
6. 此时，RemoteControl.Server.exe左侧“自动上线主机”中会看到该客户端
