### ISSUE TITLE
这个项目还维护吗? 客户端无法配置域名必须配置IP吗?

### ISSUE THREAD

**Issue by dev-kang** [frozleaf/RemoteControl#6]
配置域名提示指定了无效的IP....怎么解决下呢

**Comment by frozleaf** [comment]
supported@https://github.com/frozleaf/RemoteControl/commit/8b480c3e975003bf4f1c088682b50c4de64a6865

**Comment by dev-kang** [comment]
release能否上传下最新版本? 我这边是mac系统没法进行构建测试. 感谢.

**Comment by frozleaf** [comment]
https://github.com/frozleaf/RemoteControl/releases/tag/1.1.0

**Comment by dev-kang** [comment]
非常抱歉,又次的打扰,这个我发现填写域名还是无法找到控制端,但是填写IP是可以的,看一下是不是域名解析这块有什么问题?
Case1:
客户端配置: 服务器IP: 127.0.0.1
结果:客户端可以连接服务端

Case2:
客户端配置: 服务器IP: localhost
结果:客户端未连接服务端,服务端未显示此主机、客户端在任务管理器里面正常显示.
期望: 客户端显示在服务端的主机列表中
